name: page_list_viewport
description: A scrollable, zoomable viewport that's optimized for displaying pages of a document, such as a PDF.
version: 0.0.1
repository: https://github.com/flutter-bounty-hunters/page_list_viewport

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.1.1
  vector_math: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
